@startuml

' ******************
' Classes
' ******************

class Main {
    + static void main(String[] args)
}

' ******************
' Abstract Classes
' ******************



' ******************
' Interfaces
' ******************



' ******************
' Enums
' ******************



' ******************
' Relations
' ******************


@enduml